-- ============================================
-- COMPLETE DATABASE SCHEMA FOR HIREGO AI
-- Run this entire file in Supabase SQL Editor
-- Project: https://efnbjqtegxflijfwhvzy.supabase.co
-- ============================================

-- ==================== USERS TABLE ====================
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  role TEXT CHECK (role IN ('candidate', 'employer', 'admin')) DEFAULT 'candidate',
  status TEXT CHECK (status IN ('Active', 'Pending', 'Blocked', 'Suspended')) DEFAULT 'Active',
  phone TEXT,
  location TEXT,
  avatar_url TEXT,
  bio TEXT,
  wallet_balance DECIMAL(10,2) DEFAULT 0,
  plan TEXT DEFAULT 'Free',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== JOBS TABLE ====================
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT,
  requirements TEXT,
  skills TEXT[],
  location TEXT,
  work_mode TEXT CHECK (work_mode IN ('On-site', 'Remote', 'Hybrid')) DEFAULT 'Remote',
  type TEXT CHECK (type IN ('Full-time', 'Part-time', 'Contract', 'Freelance', 'Internship')) DEFAULT 'Full-time',
  salary_min TEXT,
  salary_max TEXT,
  status TEXT CHECK (status IN ('active', 'draft', 'closed', 'archived')) DEFAULT 'active',
  job_type TEXT DEFAULT 'basic',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== APPLICATIONS TABLE ====================
CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id),
  candidate_id TEXT REFERENCES users(id),
  status TEXT CHECK (status IN ('applied', 'pending', 'screened', 'shortlisted', 'interview_scheduled', 'hired', 'rejected')) DEFAULT 'applied',
  resume_url TEXT,
  cover_letter TEXT,
  match_score INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(job_id, candidate_id)
);

-- ==================== CANDIDATES TABLE ====================
CREATE TABLE IF NOT EXISTS candidates (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  email TEXT,
  name TEXT,
  phone TEXT,
  date_of_birth DATE,
  current_address TEXT,
  permanent_address TEXT,
  job_profile TEXT,
  education_10th JSONB,
  education_12th JSONB,
  graduation JSONB,
  post_graduation JSONB,
  bio TEXT,
  title TEXT,
  location TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE EXPERIENCE ====================
CREATE TABLE IF NOT EXISTS candidate_experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT,
  role TEXT,
  start_date TEXT,
  end_date TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE SKILLS ====================
CREATE TABLE IF NOT EXISTS candidate_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  skill TEXT,
  score INTEGER DEFAULT 80,
  category TEXT DEFAULT 'technical',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== INTERVIEWS TABLE ====================
CREATE TABLE IF NOT EXISTS interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES jobs(id),
  employer_id TEXT REFERENCES users(id),
  scheduled_date TIMESTAMP WITH TIME ZONE,
  duration INTEGER DEFAULT 60,
  status TEXT CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show')) DEFAULT 'scheduled',
  round TEXT CHECK (round IN ('screening', 'technical', 'behavioral', 'final')) DEFAULT 'screening',
  type TEXT DEFAULT 'Video',
  meeting_link TEXT,
  recording_url TEXT,
  notes TEXT,
  score INTEGER,
  proctoring_enabled BOOLEAN DEFAULT TRUE,
  proctoring_status TEXT CHECK (proctoring_status IN ('active', 'inactive', 'violation_detected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== ASSESSMENT RESULTS ====================
CREATE TABLE IF NOT EXISTS assessment_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES jobs(id),
  score INTEGER,
  communication_score INTEGER,
  knowledge_score INTEGER,
  confidence_score INTEGER,
  transcript TEXT,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== SYSTEM LOGS ====================
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT CHECK (level IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'DEBUG')),
  source TEXT,
  message TEXT NOT NULL,
  metadata JSONB,
  user_id TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== API KEYS ====================
CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  api_key TEXT,
  client_id TEXT,
  client_secret TEXT,
  access_token TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== YOUTUBE CONFIG ====================
CREATE TABLE IF NOT EXISTS youtube_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key TEXT,
  client_id TEXT,
  client_secret TEXT,
  access_token TEXT,
  channel_id TEXT,
  privacy_status TEXT DEFAULT 'private',
  auto_upload BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== EMAIL CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS email_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT CHECK (provider IN ('smtp', 'sendgrid', 'mailgun', 'ses')),
  smtp_host TEXT,
  smtp_port INTEGER,
  smtp_user TEXT,
  smtp_password TEXT,
  api_key TEXT,
  from_email TEXT,
  from_name TEXT,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== CREDIT SYSTEM ====================
CREATE TABLE IF NOT EXISTS credit_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packages JSONB,
  creditCosts JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== JOB PRICING CONFIG ====================
CREATE TABLE IF NOT EXISTS job_pricing_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basePricing JSONB,
  addons JSONB,
  discounts JSONB,
  customRules JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== PROCTORING CONFIG ====================
CREATE TABLE IF NOT EXISTS proctoring_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled BOOLEAN DEFAULT TRUE,
  settings JSONB,
  violationActions JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== AI CONFIG ====================
CREATE TABLE IF NOT EXISTS ai_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  primaryProvider TEXT DEFAULT 'gemini',
  fallbackProvider TEXT DEFAULT 'gpt4',
  features JSONB,
  weights JSONB,
  thresholds JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== PROCTORING VIOLATIONS ====================
CREATE TABLE IF NOT EXISTS proctoring_violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id),
  type TEXT CHECK (type IN ('tab-switch', 'face-not-detected', 'multiple-faces', 'exit-fullscreen', 'suspicious-activity')),
  severity TEXT CHECK (severity IN ('low', 'medium', 'high')),
  description TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  snapshot_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== TRANSACTIONS ====================
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT CHECK (type IN ('credit_purchase', 'credit_usage', 'refund', 'adjustment', 'bonus')),
  amount DECIMAL(10,2),
  credits INTEGER,
  reason TEXT,
  balance_after DECIMAL(10,2),
  payment_id TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== TRAINING LOGS ====================
CREATE TABLE IF NOT EXISTS model_training_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_source TEXT,
  status TEXT CHECK (status IN ('initiated', 'processing', 'completed', 'failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  metrics JSONB
);

-- ==================== UPSKILL: COURSES ====================
CREATE TABLE IF NOT EXISTS courses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  difficulty VARCHAR(50) DEFAULT 'beginner' CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  duration_hours INTEGER DEFAULT 0,
  lessons_count INTEGER DEFAULT 0,
  instructor VARCHAR(255),
  rating DECIMAL(2,1) DEFAULT 0,
  enrolled_count INTEGER DEFAULT 0,
  thumbnail TEXT,
  skills JSONB DEFAULT '[]',
  is_featured BOOLEAN DEFAULT false,
  price DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==================== UPSKILL: LESSONS ====================
CREATE TABLE IF NOT EXISTS lessons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  "order" INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  type VARCHAR(50) DEFAULT 'video' CHECK (type IN ('video', 'reading', 'quiz', 'interactive')),
  duration_minutes INTEGER DEFAULT 0,
  video_url TEXT,
  content TEXT,
  resources JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==================== UPSKILL: ENROLLMENTS ====================
CREATE TABLE IF NOT EXISTS user_enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  progress_percent INTEGER DEFAULT 0,
  last_accessed TIMESTAMP WITH TIME ZONE,
  status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused')),
  UNIQUE(user_id, course_id)
);

-- ==================== UPSKILL: LESSON COMPLETIONS ====================
CREATE TABLE IF NOT EXISTS lesson_completions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id UUID REFERENCES lessons(id) ON DELETE CASCADE,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  time_spent_minutes INTEGER DEFAULT 0,
  UNIQUE(user_id, lesson_id)
);

-- ==================== UPSKILL: ASSESSMENTS ====================
CREATE TABLE IF NOT EXISTS assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  passing_score INTEGER DEFAULT 70,
  time_limit_minutes INTEGER DEFAULT 30,
  questions JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==================== UPSKILL: CERTIFICATES ====================
CREATE TABLE IF NOT EXISTS certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  certificate_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID NOT NULL,
  user_name VARCHAR(255),
  course_id UUID REFERENCES courses(id) ON DELETE SET NULL,
  course_title VARCHAR(255) NOT NULL,
  course_category VARCHAR(100),
  skills_acquired JSONB DEFAULT '[]',
  instructor VARCHAR(255),
  duration_hours INTEGER,
  issued_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP WITH TIME ZONE,
  verification_url TEXT
);

-- ==================== UPSKILL: LEARNING PROGRESS ====================
CREATE TABLE IF NOT EXISTS user_learning_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL,
  total_courses_enrolled INTEGER DEFAULT 0,
  courses_completed INTEGER DEFAULT 0,
  total_lessons_completed INTEGER DEFAULT 0,
  total_hours_learned DECIMAL(10,2) DEFAULT 0,
  current_streak_days INTEGER DEFAULT 0,
  longest_streak_days INTEGER DEFAULT 0,
  certificates_earned INTEGER DEFAULT 0,
  skills_acquired JSONB DEFAULT '[]',
  skill_scores JSONB DEFAULT '{}',
  xp_points INTEGER DEFAULT 0,
  level VARCHAR(50) DEFAULT 'Beginner Learner',
  last_activity TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==================== UPSKILL: BADGES ====================
CREATE TABLE IF NOT EXISTS user_badges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  badge_id VARCHAR(100) NOT NULL,
  badge_name VARCHAR(255) NOT NULL,
  badge_description TEXT,
  badge_icon VARCHAR(50),
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, badge_id)
);

-- ==================== UPSKILL: JOB APPLICATIONS ====================
CREATE TABLE IF NOT EXISTS upskill_job_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  job_id UUID NOT NULL,
  cover_letter TEXT,
  status VARCHAR(50) DEFAULT 'submitted' CHECK (status IN ('submitted', 'viewed', 'shortlisted', 'rejected', 'hired')),
  matched_skills JSONB DEFAULT '[]',
  match_score INTEGER,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==================== INDEXES FOR PERFORMANCE ====================
CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_source ON system_logs(source);
CREATE INDEX IF NOT EXISTS idx_system_logs_created ON system_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_interviews_candidate ON interviews(candidate_id);
CREATE INDEX IF NOT EXISTS idx_interviews_job ON interviews(job_id);
CREATE INDEX IF NOT EXISTS idx_interviews_status ON interviews(status);
CREATE INDEX IF NOT EXISTS idx_violations_interview ON proctoring_violations(interview_id);
CREATE INDEX IF NOT EXISTS idx_violations_type ON proctoring_violations(type);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_featured ON courses(is_featured);
CREATE INDEX IF NOT EXISTS idx_lessons_course ON lessons(course_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_user ON user_enrollments(user_id);
CREATE INDEX IF NOT EXISTS idx_completions_user ON lesson_completions(user_id);
CREATE INDEX IF NOT EXISTS idx_certificates_user ON certificates(user_id);
CREATE INDEX IF NOT EXISTS idx_badges_user ON user_badges(user_id);

-- ==================== ENABLE ROW LEVEL SECURITY ====================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE youtube_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_pricing_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctoring_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctoring_violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_training_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_learning_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE upskill_job_applications ENABLE ROW LEVEL SECURITY;

-- ==================== PUBLIC ACCESS POLICIES ====================
-- WARNING: In production, restrict these policies!
CREATE POLICY "Public Access users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access jobs" ON jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access applications" ON applications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidates" ON candidates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidate_experience" ON candidate_experience FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidate_skills" ON candidate_skills FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access interviews" ON interviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access assessment_results" ON assessment_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to system_logs" ON system_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to api_keys" ON api_keys FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to youtube_config" ON youtube_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to email_config" ON email_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to credit_config" ON credit_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to job_pricing_config" ON job_pricing_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to proctoring_config" ON proctoring_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to ai_config" ON ai_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to proctoring_violations" ON proctoring_violations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to model_training_logs" ON model_training_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to courses" ON courses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to lessons" ON lessons FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to user_enrollments" ON user_enrollments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to lesson_completions" ON lesson_completions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to assessments" ON assessments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to certificates" ON certificates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to user_learning_progress" ON user_learning_progress FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to user_badges" ON user_badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to upskill_job_applications" ON upskill_job_applications FOR ALL USING (true) WITH CHECK (true);

-- ==================== INSERT DEFAULT CONFIGURATIONS ====================

-- Default Credit Configuration
INSERT INTO credit_config (packages, creditCosts) VALUES (
  '[
    {"id": 1, "name": "Starter", "credits": 100, "price": 9.99, "popular": false},
    {"id": 2, "name": "Professional", "credits": 500, "price": 39.99, "popular": true},
    {"id": 3, "name": "Enterprise", "credits": 2000, "price": 149.99, "popular": false}
  ]'::jsonb,
  '{
    "jobPost": 25,
    "featuredJob": 50,
    "resumeAccess": 5,
    "aiScreening": 10
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default Job Pricing Configuration
INSERT INTO job_pricing_config (basePricing, addons, discounts) VALUES (
  '{
    "standard": 25,
    "featured": 75,
    "premium": 150
  }'::jsonb,
  '{
    "urgentHiring": 20,
    "logoHighlight": 15,
    "socialPromotion": 30,
    "topPlacement": 50
  }'::jsonb,
  '{
    "bulk5": 10,
    "bulk10": 20,
    "bulk25": 30
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default Proctoring Configuration
INSERT INTO proctoring_config (enabled, settings, violationActions) VALUES (
  true,
  '{
    "faceDetection": true,
    "tabSwitchDetection": true,
    "fullscreenRequired": true,
    "recordingEnabled": true,
    "maxTabSwitches": 3,
    "warningThreshold": 2,
    "autoTerminate": true
  }'::jsonb,
  '{
    "tabSwitch": "warning",
    "faceNotDetected": "warning",
    "multipleFaces": "terminate",
    "exitFullscreen": "warning"
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default AI Configuration
INSERT INTO ai_config (primaryProvider, fallbackProvider, features, weights, thresholds) VALUES (
  'gemini',
  'gpt4',
  '{
    "resumeScreening": true,
    "videoAnalysis": true,
    "skillMapping": true,
    "rankingEngine": true,
    "continuousLearning": true
  }'::jsonb,
  '{
    "technicalSkills": 0.35,
    "communication": 0.25,
    "experience": 0.20,
    "cultureFit": 0.20
  }'::jsonb,
  '{
    "autoReject": 30,
    "autoShortlist": 80,
    "humanReview": 50
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- ==================== DEMO DATA: SAMPLE COURSES ====================
INSERT INTO courses (title, description, category, difficulty, duration_hours, lessons_count, instructor, rating, enrolled_count, is_featured, price) VALUES
('Full Stack Web Development', 'Master modern web development with React, Node.js, and databases', 'Web Development', 'intermediate', 40, 32, 'Sarah Chen', 4.8, 1250, true, 0),
('AI & Machine Learning Fundamentals', 'Learn AI/ML concepts with Python and TensorFlow', 'AI/ML', 'beginner', 25, 20, 'Dr. James Wilson', 4.9, 890, true, 0),
('Data Science with Python', 'Data analysis, visualization, and machine learning', 'Data Science', 'intermediate', 35, 28, 'Emily Rodriguez', 4.7, 720, false, 2999),
('Cloud Computing Essentials', 'AWS, Azure, and GCP fundamentals', 'Cloud Computing', 'beginner', 20, 16, 'Michael Brown', 4.6, 540, false, 1999),
('Cybersecurity Basics', 'Network security, ethical hacking, and best practices', 'Cybersecurity', 'beginner', 18, 14, 'Alex Kumar', 4.8, 680, true, 0)
ON CONFLICT DO NOTHING;

-- ============================================
-- SETUP COMPLETE!
-- ============================================
