-- Final Consolidated Database Schema for HireGo AI Portal
-- Run this in Supabase SQL Editor

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, -- Using Auth ID from Supabase
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  role TEXT CHECK (role IN ('candidate', 'employer', 'admin')) DEFAULT 'candidate',
  status TEXT CHECK (status IN ('Active', 'Pending', 'Blocked', 'Suspended')) DEFAULT 'Active',
  phone TEXT,
  location TEXT,
  avatar_url TEXT,
  bio TEXT,
  wallet_balance DECIMAL(10,2) DEFAULT 0,
  plan TEXT DEFAULT 'Free',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. JOBS TABLE
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT,
  requirements TEXT,
  skills TEXT[],
  location TEXT,
  work_mode TEXT CHECK (work_mode IN ('On-site', 'Remote', 'Hybrid')) DEFAULT 'Remote',
  type TEXT CHECK (type IN ('Full-time', 'Part-time', 'Contract', 'Freelance', 'Internship')) DEFAULT 'Full-time',
  salary_min TEXT,
  salary_max TEXT,
  status TEXT CHECK (status IN ('active', 'draft', 'closed', 'archived')) DEFAULT 'active',
  job_type TEXT DEFAULT 'basic', -- basic, standard, premium, urgent, interview-ready
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id),
  candidate_id TEXT REFERENCES users(id),
  status TEXT CHECK (status IN ('applied', 'pending', 'screened', 'shortlisted', 'interview_scheduled', 'hired', 'rejected')) DEFAULT 'applied',
  resume_url TEXT,
  cover_letter TEXT,
  match_score INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(job_id, candidate_id)
);

-- 4. CANDIDATES TABLE
CREATE TABLE IF NOT EXISTS candidates (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  email TEXT,
  name TEXT,
  phone TEXT,
  date_of_birth DATE,
  current_address TEXT,
  permanent_address TEXT,
  job_profile TEXT,
  education_10th JSONB,
  education_12th JSONB,
  graduation JSONB,
  post_graduation JSONB,
  bio TEXT,
  title TEXT,
  location TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. CANDIDATE EXPERIENCE
CREATE TABLE IF NOT EXISTS candidate_experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT,
  role TEXT,
  start_date TEXT,
  end_date TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. CANDIDATE SKILLS
CREATE TABLE IF NOT EXISTS candidate_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  skill TEXT,
  score INTEGER DEFAULT 80,
  category TEXT DEFAULT 'technical',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. INTERVIEWS (Improved)
CREATE TABLE IF NOT EXISTS interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES jobs(id),
  employer_id TEXT REFERENCES users(id),
  scheduled_date TIMESTAMP WITH TIME ZONE,
  duration INTEGER DEFAULT 60,
  status TEXT CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show')) DEFAULT 'scheduled',
  round TEXT CHECK (round IN ('screening', 'technical', 'behavioral', 'final')) DEFAULT 'screening',
  type TEXT DEFAULT 'Video',
  meeting_link TEXT,
  recording_url TEXT,
  notes TEXT,
  score INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. ASSESSMENT RESULTS
CREATE TABLE IF NOT EXISTS assessment_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES jobs(id),
  score INTEGER,
  communication_score INTEGER,
  knowledge_score INTEGER,
  confidence_score INTEGER,
  transcript TEXT,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;

-- Public policies
CREATE POLICY "Public Access users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access jobs" ON jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access applications" ON applications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidates" ON candidates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidate_experience" ON candidate_experience FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access candidate_skills" ON candidate_skills FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access interviews" ON interviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access assessment_results" ON assessment_results FOR ALL USING (true) WITH CHECK (true);
