-- Extended Database Schema for AI Recruitment Intelligence System
-- Run this in Supabase SQL Editor after the base schema

-- ==================== CANDIDATE EVALUATIONS ====================
CREATE TABLE IF NOT EXISTS candidate_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL,
  candidate_name TEXT,
  candidate_email TEXT,
  job_id TEXT,
  job_title TEXT,
  
  -- Evaluation Scores
  screening_score INTEGER,
  technical_score INTEGER,
  behavioral_score INTEGER,
  final_score INTEGER,
  
  -- Detailed Results
  screening_details JSONB,
  technical_details JSONB,
  behavioral_details JSONB,
  
  -- Video Analysis
  video_url TEXT,
  transcription TEXT,
  video_analysis JSONB,
  
  -- Metadata
  evaluation_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  processing_time INTEGER, -- milliseconds
  agent_version TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== EMPLOYER FEEDBACK ====================
CREATE TABLE IF NOT EXISTS employer_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT,
  candidate_id TEXT NOT NULL,
  employer_id TEXT NOT NULL,
  
  -- Feedback Ratings (1-5 scale)
  technical_rating INTEGER CHECK (technical_rating BETWEEN 1 AND 5),
  communication_rating INTEGER CHECK (communication_rating BETWEEN 1 AND 5),
  culture_fit_rating INTEGER CHECK (culture_fit_rating BETWEEN 1 AND 5),
  overall_rating INTEGER CHECK (overall_rating BETWEEN 1 AND 5),
  
  -- Structured Feedback
  strengths TEXT[],
  weaknesses TEXT[],
  detailed_comments TEXT,
  
  -- Decision
  hiring_decision TEXT CHECK (hiring_decision IN ('hire', 'reject', 'maybe', 'next_round')),
  rejection_reason TEXT,
  
  -- Mandatory Flag
  is_mandatory BOOLEAN DEFAULT TRUE,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Learning Integration
  used_for_training BOOLEAN DEFAULT FALSE,
  training_date TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE RANKINGS ====================
CREATE TABLE IF NOT EXISTS candidate_rankings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL,
  job_id TEXT NOT NULL,
  
  -- Ranking Scores
  composite_score DECIMAL(5,2),
  rank_position INTEGER,
  percentile DECIMAL(5,2),
  
  -- Score Components
  skill_match_score DECIMAL(5,2),
  experience_score DECIMAL(5,2),
  interview_score DECIMAL(5,2),
  feedback_score DECIMAL(5,2),
  past_success_score DECIMAL(5,2),
  
  -- Metadata
  total_candidates INTEGER,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Unique constraint
  UNIQUE(candidate_id, job_id)
);

-- ==================== SKILL MAPPINGS ====================
CREATE TABLE IF NOT EXISTS skill_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_role TEXT NOT NULL,
  
  -- Required Skills
  required_skills JSONB, -- {skill: weight}
  optional_skills JSONB,
  
  -- Skill Categories
  technical_skills TEXT[],
  soft_skills TEXT[],
  domain_skills TEXT[],
  
  -- Scoring Weights
  technical_weight DECIMAL(3,2) DEFAULT 0.40,
  soft_weight DECIMAL(3,2) DEFAULT 0.30,
  domain_weight DECIMAL(3,2) DEFAULT 0.30,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE,
  
  UNIQUE(job_role)
);

-- ==================== MODEL TRAINING LOGS ====================
CREATE TABLE IF NOT EXISTS model_training_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Training Info
  training_type TEXT CHECK (training_type IN ('auto', 'manual', 'scheduled')),
  trigger_event TEXT, -- 'new_hire', 'feedback_received', 'scheduled'
  
  -- Data Used
  training_data_count INTEGER,
  feedback_count INTEGER,
  evaluation_count INTEGER,
  
  -- Model Performance
  accuracy_before DECIMAL(5,2),
  accuracy_after DECIMAL(5,2),
  improvement DECIMAL(5,2),
  
  -- Weights Updated
  model_weights JSONB,
  
  -- Execution Details
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  duration INTEGER, -- seconds
  status TEXT CHECK (status IN ('running', 'completed', 'failed')),
  error_message TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== VIDEO ANALYSIS RESULTS ====================
CREATE TABLE IF NOT EXISTS video_analysis_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL,
  video_url TEXT,
  
  -- Transcription
  transcription TEXT,
  transcription_confidence DECIMAL(5,2),
  
  -- Sentiment Analysis
  overall_sentiment TEXT CHECK (overall_sentiment IN ('positive', 'neutral', 'negative', 'professional')),
  sentiment_score DECIMAL(5,2),
  
  -- Communication Metrics
  clarity_score DECIMAL(5,2),
  confidence_score DECIMAL(5,2),
  engagement_score DECIMAL(5,2),
  hesitation_count INTEGER,
  filler_words_count INTEGER,
  
  -- Non-Verbal Analysis
  eye_contact_score DECIMAL(5,2),
  posture_score DECIMAL(5,2),
  facial_expression_analysis JSONB,
  
  -- Technical Details
  video_duration INTEGER, -- seconds
  audio_quality TEXT,
  processing_time INTEGER, -- milliseconds
  
  -- Keywords & Topics
  detected_keywords TEXT[],
  topic_analysis JSONB,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== SYSTEM PERFORMANCE METRICS ====================
CREATE TABLE IF NOT EXISTS system_performance_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_date DATE NOT NULL,
  
  -- Hiring Metrics
  total_applications INTEGER DEFAULT 0,
  total_interviews INTEGER DEFAULT 0,
  total_hires INTEGER DEFAULT 0,
  hiring_success_rate DECIMAL(5,2),
  interview_to_selection_ratio DECIMAL(5,2),
  
  -- Agent Performance
  avg_screening_time INTEGER, -- milliseconds
  avg_technical_analysis_time INTEGER,
  avg_behavioral_analysis_time INTEGER,
  avg_video_processing_time INTEGER,
  
  -- Model Accuracy
  model_accuracy DECIMAL(5,2),
  prediction_accuracy DECIMAL(5,2),
  false_positive_rate DECIMAL(5,2),
  false_negative_rate DECIMAL(5,2),
  
  -- Cost Metrics
  total_api_calls INTEGER,
  gemini_api_calls INTEGER,
  gpt4_api_calls INTEGER,
  estimated_cost DECIMAL(10,2),
  
  -- Feedback Metrics
  feedback_submission_rate DECIMAL(5,2),
  avg_feedback_rating DECIMAL(3,2),
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(metric_date)
);

-- ==================== INDEXES FOR PERFORMANCE ====================

CREATE INDEX idx_candidate_evaluations_candidate ON candidate_evaluations(candidate_id);
CREATE INDEX idx_candidate_evaluations_job ON candidate_evaluations(job_id);
CREATE INDEX idx_candidate_evaluations_date ON candidate_evaluations(evaluation_date);

CREATE INDEX idx_employer_feedback_candidate ON employer_feedback(candidate_id);
CREATE INDEX idx_employer_feedback_employer ON employer_feedback(employer_id);
CREATE INDEX idx_employer_feedback_interview ON employer_feedback(interview_id);
CREATE INDEX idx_employer_feedback_training ON employer_feedback(used_for_training);

CREATE INDEX idx_candidate_rankings_candidate ON candidate_rankings(candidate_id);
CREATE INDEX idx_candidate_rankings_job ON candidate_rankings(job_id);
CREATE INDEX idx_candidate_rankings_score ON candidate_rankings(composite_score DESC);

CREATE INDEX idx_video_analysis_candidate ON video_analysis_results(candidate_id);
CREATE INDEX idx_video_analysis_date ON video_analysis_results(created_at);

CREATE INDEX idx_training_logs_date ON model_training_logs(created_at);
CREATE INDEX idx_training_logs_status ON model_training_logs(status);

CREATE INDEX idx_performance_metrics_date ON system_performance_metrics(metric_date);

-- ==================== ROW LEVEL SECURITY ====================

ALTER TABLE candidate_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE employer_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_training_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_analysis_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_performance_metrics ENABLE ROW LEVEL SECURITY;

-- Public access policies (adjust for production)
CREATE POLICY "Allow public access to candidate_evaluations" ON candidate_evaluations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to employer_feedback" ON employer_feedback FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_rankings" ON candidate_rankings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to skill_mappings" ON skill_mappings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to model_training_logs" ON model_training_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to video_analysis_results" ON video_analysis_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to system_performance_metrics" ON system_performance_metrics FOR ALL USING (true) WITH CHECK (true);

-- ==================== FUNCTIONS & TRIGGERS ====================

-- Function to update candidate rankings when new evaluation is added
CREATE OR REPLACE FUNCTION update_candidate_ranking()
RETURNS TRIGGER AS $$
BEGIN
  -- This will be called by the ranking engine
  -- Placeholder for now
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update rankings
CREATE TRIGGER trigger_update_ranking
AFTER INSERT OR UPDATE ON candidate_evaluations
FOR EACH ROW
EXECUTE FUNCTION update_candidate_ranking();

-- Function to track daily metrics
CREATE OR REPLACE FUNCTION update_daily_metrics()
RETURNS void AS $$
BEGIN
  INSERT INTO system_performance_metrics (metric_date)
  VALUES (CURRENT_DATE)
  ON CONFLICT (metric_date) DO NOTHING;
END;
$$ LANGUAGE plpgsql;
