-- Run this SQL in your Supabase Dashboard -> SQL Editor

-- Table: system_logs
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  level TEXT,
  message TEXT,
  source TEXT
);

-- Table: interviews
-- Using quoted identifiers to match frontend camelCase interfaces
CREATE TABLE IF NOT EXISTS interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candidateName" TEXT,
  role TEXT,
  date TIMESTAMP WITH TIME ZONE,
  time TEXT,
  type TEXT,
  status TEXT,
  avatar TEXT,
  participants TEXT[],
  "roundTag" TEXT
);

-- Enable RLS (Optional but recommended)
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read/write for now (since we are using anon key and this is a demo/dev setup)
-- WARNING: In production, you should restrict these policies!
CREATE POLICY "Allow public access to system_logs" ON system_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to interviews" ON interviews FOR ALL USING (true) WITH CHECK (true);

-- Table: api_keys
CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  api_key TEXT,
  client_id TEXT,
  client_secret TEXT,
  access_token TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Table: youtube_config
CREATE TABLE IF NOT EXISTS youtube_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key TEXT,
  client_id TEXT,
  client_secret TEXT,
  access_token TEXT,
  channel_id TEXT,
  privacy_status TEXT DEFAULT 'private',
  auto_upload BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- RLS for new tables
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE youtube_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to api_keys" ON api_keys FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to youtube_config" ON youtube_config FOR ALL USING (true) WITH CHECK (true);
