-- 1. Video Analysis Results Table
CREATE TABLE IF NOT EXISTS video_analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT REFERENCES users(id),
    video_url TEXT,
    transcription TEXT,
    transcription_confidence DECIMAL,
    overall_sentiment TEXT,
    sentiment_score INTEGER,
    clarity_score INTEGER,
    confidence_score INTEGER,
    engagement_score INTEGER,
    hesitation_count INTEGER,
    filler_words_count INTEGER,
    eye_contact_score INTEGER,
    posture_score INTEGER,
    facial_expression_analysis JSONB,
    video_duration DECIMAL,
    audio_quality TEXT,
    processing_time INTEGER,
    detected_keywords TEXT[],
    topic_analysis JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Gamification Badges Table
CREATE TABLE IF NOT EXISTS gamification_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT, -- Lucide icon name or URL
    category TEXT CHECK (category IN ('Skill', 'Behavioral', 'Achievement', 'Streak')),
    xp_value INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Gamification User Badges (Join Table)
CREATE TABLE IF NOT EXISTS gamification_user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    badge_id BIGINT REFERENCES gamification_badges(id),
    earned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Gamification Challenges
CREATE TABLE IF NOT EXISTS gamification_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT CHECK (type IN ('Daily', 'Weekly', 'Special')),
    reward_xp INTEGER,
    status TEXT DEFAULT 'active',
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. User Gamification Stats
CREATE TABLE IF NOT EXISTS gamification_stats (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    level INTEGER DEFAULT 1,
    current_xp INTEGER DEFAULT 0,
    next_level_xp INTEGER DEFAULT 1000,
    streak_days INTEGER DEFAULT 0,
    total_badges INTEGER DEFAULT 0,
    leaderboard_rank INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE video_analysis_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_stats ENABLE ROW LEVEL SECURITY;

-- Public Policies (Simplistic for now)
CREATE POLICY "Public Access video_analysis_results" ON video_analysis_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access gamification_badges" ON gamification_badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access gamification_user_badges" ON gamification_user_badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access gamification_challenges" ON gamification_challenges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access gamification_stats" ON gamification_stats FOR ALL USING (true) WITH CHECK (true);

-- SEED DATA: Badges
INSERT INTO gamification_badges (name, description, icon, category, xp_value) VALUES
('First Impression', 'Completed your profile and uploaded a resume', 'UserCheck', 'Achievement', 100),
('Interview Ready', 'Completed a mock AI interview', 'Video', 'Skill', 200),
('Code Warrior', 'Passed a technical coding assessment', 'Code', 'Skill', 500),
('Consistent Learner', 'Logged in for 7 consecutive days', 'Flame', 'Streak', 300),
('Communicator', 'Scored >90% in communication skills', 'Mic', 'Behavioral', 250);

-- SEED DATA: Challenges
INSERT INTO gamification_challenges (title, description, type, reward_xp, deadline) VALUES
('Complete Profile', 'Fill out 100% of your profile details.', 'Daily', 150, NOW() + INTERVAL '1 day'),
('Practice Makes Perfect', 'Take 3 mock interviews this week.', 'Weekly', 500, NOW() + INTERVAL '7 days'),
('Resume Polish', 'Update your resume with new skills.', 'Daily', 100, NOW() + INTERVAL '1 day');
