-- Gamification and Portfolio Schema
-- Run this in Supabase SQL Editor to enable Gamification features

-- 1. GAMIFICATION STATS
CREATE TABLE IF NOT EXISTS gamification_stats (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    level TEXT DEFAULT 'Bronze',
    points INTEGER DEFAULT 0,
    next_level_points INTEGER DEFAULT 1000,
    global_rank INTEGER DEFAULT 0,
    total_candidates INTEGER DEFAULT 0,
    skill_mastery INTEGER DEFAULT 0,
    correct_rate INTEGER DEFAULT 0,
    challenges_completed INTEGER DEFAULT 0,
    total_attempts INTEGER DEFAULT 0,
    streak INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. BADGES DEFINITION
CREATE TABLE IF NOT EXISTS badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT, -- Lucide icon name or URL
    color TEXT,
    category TEXT
);

-- 3. USER BADGES
CREATE TABLE IF NOT EXISTS user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    badge_id BIGINT REFERENCES badges(id),
    earned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CHALLENGES
CREATE TABLE IF NOT EXISTS challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT, -- Frontend, Backend, AI, etc.
    points INTEGER DEFAULT 50,
    difficulty TEXT CHECK (difficulty IN ('Easy', 'Medium', 'Hard')) DEFAULT 'Medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. GAMIFICATION HISTORY (for graphs)
CREATE TABLE IF NOT EXISTS gamification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    score INTEGER, -- Points or Mastery Score at that time
    date DATE DEFAULT CURRENT_DATE
);

-- 6. PORTFOLIO ITEMS
CREATE TABLE IF NOT EXISTS portfolio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT,
    link TEXT,
    image_url TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE gamification_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio_items ENABLE ROW LEVEL SECURITY;

-- Public Access Policies
CREATE POLICY "Public Access gamification_stats" ON gamification_stats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access badges" ON badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access user_badges" ON user_badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access challenges" ON challenges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access gamification_history" ON gamification_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access portfolio_items" ON portfolio_items FOR ALL USING (true) WITH CHECK (true);

-- Seed Initial Badges
INSERT INTO badges (name, description, icon, color, category) VALUES
('Early Adopter', 'Joined the platform early', 'Star', 'text-yellow-400', 'Community'),
('Skill Master', 'Achieved 90% mastery in a skill', 'Trophy', 'text-purple-400', 'Skill'),
('Bug Hunter', 'Found and reported a bug', 'Bug', 'text-red-400', 'Community'),
('Consistent Learner', '7 day streak', 'Zap', 'text-blue-400', 'Activity');

-- Seed Initial Challenges
INSERT INTO challenges (title, description, category, points, difficulty) VALUES
('React Component Optimization', 'Optimize a React component for rendering performance', 'Frontend', 100, 'Medium'),
('API Rate Limiting', 'Implement rate limiting for an Express API', 'Backend', 150, 'Hard'),
('CSS Grid Layout', 'Create a responsive layout using CSS Grid', 'Frontend', 50, 'Easy');
