-- Additional Database Schema for Admin Panel Configuration Tables
-- Run this in Supabase SQL Editor after the base and extended schemas

-- ==================== SYSTEM LOGS ====================
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT CHECK (level IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'DEBUG')),
  source TEXT, -- e.g., 'AuthService', 'AIProvider', 'VideoService'
  message TEXT NOT NULL,
  metadata JSONB,
  user_id TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== MODEL TRAINING LOGS ====================
CREATE TABLE IF NOT EXISTS model_training_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_source TEXT,
  status TEXT CHECK (status IN ('initiated', 'processing', 'completed', 'failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  metrics JSONB
);

-- ==================== EMAIL CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS email_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT CHECK (provider IN ('smtp', 'sendgrid', 'mailgun', 'ses')),
  smtp_host TEXT,
  smtp_port INTEGER,
  smtp_user TEXT,
  smtp_password TEXT, -- Encrypted
  api_key TEXT, -- Encrypted
  from_email TEXT,
  from_name TEXT,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== CREDIT SYSTEM CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS credit_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packages JSONB, -- Array of credit packages
  creditCosts JSONB, -- Cost configuration for various actions
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== JOB PRICING CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS job_pricing_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basePricing JSONB, -- Base pricing for job types
  addons JSONB, -- Addon pricing
  discounts JSONB, -- Bulk discounts
  customRules JSONB, -- Custom pricing rules
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== PROCTORING CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS proctoring_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled BOOLEAN DEFAULT TRUE,
  settings JSONB, -- Proctoring settings
  violationActions JSONB, -- Actions for different violations
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== AI SYSTEM CONFIGURATION ====================
CREATE TABLE IF NOT EXISTS ai_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  primaryProvider TEXT DEFAULT 'gemini',
  fallbackProvider TEXT DEFAULT 'gpt4',
  features JSONB, -- Enabled AI features
  weights JSONB, -- Scoring weights
  thresholds JSONB, -- Decision thresholds
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== INTERVIEWS TABLE ====================
CREATE TABLE IF NOT EXISTS interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL,
  job_id TEXT NOT NULL,
  employer_id TEXT,
  
  -- Scheduling
  scheduled_date TIMESTAMP WITH TIME ZONE,
  duration INTEGER DEFAULT 60, -- minutes
  
  -- Status
  status TEXT CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show')),
  round TEXT CHECK (round IN ('screening', 'technical', 'behavioral', 'final')),
  
  -- Proctoring
  proctoring_enabled BOOLEAN DEFAULT TRUE,
  proctoring_status TEXT CHECK (proctoring_status IN ('active', 'inactive', 'violation_detected')),
  recording_url TEXT,
  
  -- Results
  notes TEXT,
  score INTEGER,
  decision TEXT CHECK (decision IN ('pass', 'fail', 'pending')),
  
  -- Metadata
  interviewers TEXT[],
  meeting_link TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- ==================== PROCTORING VIOLATIONS ====================
CREATE TABLE IF NOT EXISTS proctoring_violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id),
  type TEXT CHECK (type IN ('tab-switch', 'face-not-detected', 'multiple-faces', 'exit-fullscreen', 'suspicious-activity')),
  severity TEXT CHECK (severity IN ('low', 'medium', 'high')),
  description TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  snapshot_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== TRANSACTIONS ====================
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT CHECK (type IN ('credit_purchase', 'credit_usage', 'refund', 'adjustment', 'bonus')),
  amount DECIMAL(10,2),
  credits INTEGER,
  reason TEXT,
  balance_after DECIMAL(10,2),
  payment_id TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== INDEXES FOR PERFORMANCE ====================

CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_source ON system_logs(source);
CREATE INDEX IF NOT EXISTS idx_system_logs_created ON system_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_interviews_candidate ON interviews(candidate_id);
CREATE INDEX IF NOT EXISTS idx_interviews_job ON interviews(job_id);
CREATE INDEX IF NOT EXISTS idx_interviews_status ON interviews(status);
CREATE INDEX IF NOT EXISTS idx_interviews_date ON interviews(scheduled_date);

CREATE INDEX IF NOT EXISTS idx_violations_interview ON proctoring_violations(interview_id);
CREATE INDEX IF NOT EXISTS idx_violations_type ON proctoring_violations(type);

CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_created ON transactions(created_at);

-- ==================== ROW LEVEL SECURITY ====================

ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_pricing_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctoring_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctoring_violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Public access policies (adjust for production - should be restricted to admins)
CREATE POLICY "Allow public access to system_logs" ON system_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to email_config" ON email_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to credit_config" ON credit_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to job_pricing_config" ON job_pricing_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to proctoring_config" ON proctoring_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to ai_config" ON ai_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to interviews" ON interviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to proctoring_violations" ON proctoring_violations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);

-- ==================== INSERT DEFAULT CONFIGURATIONS ====================

-- Default Credit Configuration
INSERT INTO credit_config (packages, creditCosts) VALUES (
  '[
    {"id": 1, "name": "Starter", "credits": 100, "price": 9.99, "popular": false},
    {"id": 2, "name": "Professional", "credits": 500, "price": 39.99, "popular": true},
    {"id": 3, "name": "Enterprise", "credits": 2000, "price": 149.99, "popular": false}
  ]'::jsonb,
  '{
    "jobPost": 25,
    "featuredJob": 50,
    "resumeAccess": 5,
    "aiScreening": 10
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default Job Pricing Configuration
INSERT INTO job_pricing_config (basePricing, addons, discounts) VALUES (
  '{
    "standard": 25,
    "featured": 75,
    "premium": 150
  }'::jsonb,
  '{
    "urgentHiring": 20,
    "logoHighlight": 15,
    "socialPromotion": 30,
    "topPlacement": 50
  }'::jsonb,
  '{
    "bulk5": 10,
    "bulk10": 20,
    "bulk25": 30
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default Proctoring Configuration
INSERT INTO proctoring_config (enabled, settings, violationActions) VALUES (
  true,
  '{
    "faceDetection": true,
    "tabSwitchDetection": true,
    "fullscreenRequired": true,
    "recordingEnabled": true,
    "maxTabSwitches": 3,
    "warningThreshold": 2,
    "autoTerminate": true
  }'::jsonb,
  '{
    "tabSwitch": "warning",
    "faceNotDetected": "warning",
    "multipleFaces": "terminate",
    "exitFullscreen": "warning"
  }'::jsonb
) ON CONFLICT DO NOTHING;

-- Default AI Configuration
INSERT INTO ai_config (primaryProvider, fallbackProvider, features, weights, thresholds) VALUES (
  'gemini',
  'gpt4',
  '{
    "resumeScreening": true,
    "videoAnalysis": true,
    "skillMapping": true,
    "rankingEngine": true,
    "continuousLearning": true
  }'::jsonb,
  '{
    "technicalSkills": 0.35,
    "communication": 0.25,
    "experience": 0.20,
    "cultureFit": 0.20
  }'::jsonb,
  '{
    "autoReject": 30,
    "autoShortlist": 80,
    "humanReview": 50
  }'::jsonb
) ON CONFLICT DO NOTHING;
