-- Candidates and Related Tables Schema
-- Run this in Supabase SQL Editor

-- ==================== CANDIDATES TABLE ====================
CREATE TABLE IF NOT EXISTS candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Basic Info
  email TEXT NOT NULL,
  name TEXT,
  phone TEXT,
  avatar_url TEXT,
  
  -- Personal Details (from registration form)
  date_of_birth TEXT,
  current_address TEXT,
  permanent_address TEXT,
  
  -- Professional Info
  title TEXT,
  job_profile TEXT,
  bio TEXT,
  location TEXT,
  
  -- Education (stored as JSONB from registration form)
  education_10th JSONB DEFAULT '{}'::jsonb,
  education_12th JSONB DEFAULT '{}'::jsonb,
  graduation JSONB DEFAULT '{}'::jsonb,
  post_graduation JSONB DEFAULT '{}'::jsonb,
  
  -- Skills and Experience
  skills TEXT[] DEFAULT ARRAY[]::TEXT[],
  experience_years INTEGER DEFAULT 0,
  
  -- Video Resume
  video_resume_url TEXT,
  video_analysis JSONB,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE SKILLS TABLE ====================
CREATE TABLE IF NOT EXISTS candidate_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  skill TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  category TEXT, -- 'technical', 'soft', 'domain'
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(user_id, skill)
);

-- ==================== CANDIDATE EXPERIENCE TABLE ====================
CREATE TABLE IF NOT EXISTS candidate_experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  start_date TEXT,
  end_date TEXT,
  description TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE EDUCATION TABLE ====================
CREATE TABLE IF NOT EXISTS candidate_education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  degree TEXT NOT NULL,
  institution TEXT,
  start_year TEXT,
  end_year TEXT,
  description TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== CANDIDATE PORTFOLIO TABLE ====================
CREATE TABLE IF NOT EXISTS candidate_portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  project_url TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== GAMIFICATION STATS TABLE ====================
CREATE TABLE IF NOT EXISTS gamification_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  rank INTEGER DEFAULT 0,
  points INTEGER DEFAULT 0,
  mastery_score INTEGER DEFAULT 0,
  accuracy INTEGER DEFAULT 0,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(user_id)
);

-- ==================== BADGES TABLE ====================
CREATE TABLE IF NOT EXISTS badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  criteria JSONB,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(name)
);

-- ==================== USER BADGES TABLE ====================
CREATE TABLE IF NOT EXISTS user_badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  badge_id BIGINT REFERENCES badges(id) ON DELETE CASCADE,
  
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(user_id, badge_id)
);

-- ==================== ASSESSMENT RESULTS TABLE ====================
CREATE TABLE IF NOT EXISTS assessment_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id BIGINT,
  
  score INTEGER DEFAULT 0,
  communication_score INTEGER DEFAULT 0,
  knowledge_score INTEGER DEFAULT 0,
  confidence_score INTEGER DEFAULT 0,
  
  questions_data JSONB,
  answers_data JSONB,
  
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== INDEXES ====================
CREATE INDEX IF NOT EXISTS idx_candidates_user_id ON candidates(user_id);
CREATE INDEX IF NOT EXISTS idx_candidates_email ON candidates(email);
CREATE INDEX IF NOT EXISTS idx_candidate_skills_user_id ON candidate_skills(user_id);
CREATE INDEX IF NOT EXISTS idx_candidate_experience_user_id ON candidate_experience(user_id);
CREATE INDEX IF NOT EXISTS idx_candidate_education_user_id ON candidate_education(user_id);
CREATE INDEX IF NOT EXISTS idx_candidate_portfolio_user_id ON candidate_portfolio(user_id);
CREATE INDEX IF NOT EXISTS idx_gamification_stats_user_id ON gamification_stats(user_id);
CREATE INDEX IF NOT EXISTS idx_user_badges_user_id ON user_badges(user_id);
CREATE INDEX IF NOT EXISTS idx_assessment_results_user_id ON assessment_results(user_id);

-- ==================== ROW LEVEL SECURITY ====================
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_education ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamification_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;

-- Public access policies (adjust for production)
CREATE POLICY "Allow public access to candidates" ON candidates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_skills" ON candidate_skills FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_experience" ON candidate_experience FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_education" ON candidate_education FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_portfolio" ON candidate_portfolio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to gamification_stats" ON gamification_stats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to badges" ON badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to user_badges" ON user_badges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to assessment_results" ON assessment_results FOR ALL USING (true) WITH CHECK (true);

-- ==================== SEED DATA ====================
-- Insert some default badges
INSERT INTO badges (name, description, icon) VALUES
('First Assessment', 'Completed your first video assessment', 'trophy'),
('Skill Master', 'Achieved 90%+ in technical skills', 'star'),
('Top Communicator', 'Excellent communication scores', 'message-circle')
ON CONFLICT (name) DO NOTHING;
