-- Job Titles and Skills Management Tables
-- Run this in Supabase SQL Editor

-- ==================== JOB TITLES TABLE ====================
CREATE TABLE IF NOT EXISTS job_titles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== JOB TITLE SKILLS TABLE ====================
-- Stores AI-generated or cached skills for each job title
CREATE TABLE IF NOT EXISTS job_title_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_title TEXT NOT NULL UNIQUE,
  skills TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== INDEXES ====================
CREATE INDEX IF NOT EXISTS idx_job_titles_title ON job_titles(title);
CREATE INDEX IF NOT EXISTS idx_job_title_skills_title ON job_title_skills(job_title);

-- ==================== ROW LEVEL SECURITY ====================
ALTER TABLE job_titles ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_title_skills ENABLE ROW LEVEL SECURITY;

-- Public access policies (adjust for production)
CREATE POLICY "Allow public access to job_titles" ON job_titles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to job_title_skills" ON job_title_skills FOR ALL USING (true) WITH CHECK (true);

-- ==================== SEED DATA ====================
-- Insert some common job titles
INSERT INTO job_titles (title) VALUES
('Software Engineer'),
('Senior Software Engineer'),
('Frontend Developer'),
('Backend Developer'),
('Full Stack Developer'),
('Data Scientist'),
('Data Analyst'),
('Product Manager'),
('UI/UX Designer'),
('DevOps Engineer'),
('Mobile App Developer'),
('QA Engineer'),
('Business Analyst'),
('Project Manager'),
('Marketing Manager')
ON CONFLICT (title) DO NOTHING;
